# Generated by Django 3.2 on 2021-04-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='user_password',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='password',
            field=models.CharField(max_length=11, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(max_length=55, null=True, verbose_name='username'),
        ),
    ]
