# Generated by Django 3.2 on 2021-04-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210430_0251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatUser',
        ),
    ]
